//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public Kategoriler()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int KategoriId { get; set; }
        public string Kategori { get; set; }
    
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
