//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunId { get; set; }
        public string Adi { get; set; }
        public decimal Fiyati { get; set; }
        public string KucukGorsel { get; set; }
        public int KategoriId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
